#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later

ima_genkey_mldsa()
{
	keyalgo="$1"

	GENKEY=ima.genkey

	maj=$(openssl version | awk '{print $2}' | cut -d. -f1)
	min=$(openssl version | awk '{print $2}' | cut -d. -f2)

	if [ "${maj}" -lt 3 ] || { [ "${maj}" -eq 3 ] && [ "${min}" -lt 5 ]; }; then
		echo "The openssl tool is too old (v${maj}.${min}) to support ML-DSA. Need at least v3.5.0."
		exit 1
	fi
	cat << __EOF__ >$GENKEY
[ req ]
distinguished_name = req_distinguished_name
prompt = no
string_mask = utf8only
x509_extensions = v3_usr

[ req_distinguished_name ]
O = $(hostname)
CN = $(whoami) signing key
emailAddress = $(whoami)@$(hostname)

[ v3_usr ]
basicConstraints=critical,CA:FALSE
#basicConstraints=CA:FALSE
keyUsage=digitalSignature
#keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage=critical,codeSigning
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
#authorityKeyIdentifier=keyid,issuer
__EOF__

	openssl req -new -nodes -batch -config $GENKEY \
			-out csr_ima.pem -keyout privkey_ima.pem \
			-newkey "${keyalgo}" || return $?
	openssl x509 -req -in csr_ima.pem -days 365 -extfile $GENKEY -extensions v3_usr \
			-CA ima-local-ca.pem -CAkey ima-local-ca.priv -CAcreateserial \
			-outform DER -out x509_ima.der
	return $?
}
