#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later

# Get the OpenSSL keyalgo parameter
# @param1: The key algorithm; must be a name that OpenSSL command line tool
#          accepts
get_ossl_keyalgo()
{
	case "$1" in
	rsa:2048)
		echo "$1"
		;;
	prime256v1)
		echo "ec"
		;;
	esac
}

# Get the OpenSSL -pkeyopt that may be necessary for the given key algo
# @param1: The key algorithm; must be a name that OpenSSL command line tool
#          accepts
get_ossl_keyalgo_detail()
{
	case "$1" in
	rsa:2048)
		echo ""
		;;
	prime256v1)
		echo "-pkeyopt ec_paramgen_curve:${keyalgo}"
		;;
	esac
}

# Create an IMA file signing key
# @param1: The key algorithm; must be a name that OpenSSL command line tool
#          accepts: rsa:2048, rsa:3072, rsa:4096, prime256v1
ima_gen_signing_key()
{
	keyalgo="$1"

	GENKEY=ima.genkey

	ossl_keyalgo=$(get_ossl_keyalgo "$keyalgo")
	if [ -z "$ossl_keyalgo" ]; then
		echo "Error: Unsupported key algorithm $keyalgo." >&2
		return 1
	fi
	ossl_keyalgo_detail=$(get_ossl_keyalgo_detail "$keyalgo")

	cat << __EOF__ >$GENKEY
[ req ]
distinguished_name = req_distinguished_name
prompt = no
string_mask = utf8only
x509_extensions = v3_usr

[ req_distinguished_name ]
O = $(hostname)
CN = $(whoami) signing key
emailAddress = $(whoami)@$(hostname)

[ v3_usr ]
basicConstraints=critical,CA:FALSE
#basicConstraints=CA:FALSE
keyUsage=digitalSignature
#keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage=critical,codeSigning
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
#authorityKeyIdentifier=keyid,issuer
__EOF__

	openssl req -new -nodes -batch -config $GENKEY \
		-out csr_ima.pem -keyout privkey_ima.pem \
		-newkey "${ossl_keyalgo}" \
		${ossl_keyalgo_detail:+${ossl_keyalgo_detail}} || return $?
	openssl x509 -req -in csr_ima.pem -days 365 -extfile $GENKEY -extensions v3_usr \
		-CA ima-local-ca.pem -CAkey ima-local-ca.priv -CAcreateserial \
		-outform DER -out x509_ima.der
	return $?
}
